포스팅디테일뷰 & 댓글 기능 생성
wecode-bootcamp-korea/28-2nd-Barracks-backend pull request #4
Opened 2022-01-13 09:40 UTC by wsji91

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 포스팅상세페이지와 그것에 붙어있는 댓글 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 포스팅상세뷰
- posting_id를 기준으로 받아서 필요한 내용들을 참조하여 나타낸다.
- posting과 user 관련하여 에러사황 처리를 나타낸다.

2. 댓글 post, get, delete
- 댓글을 작성할 수 있게 구현하고, 댓글마다 user 정보와 댓글(comment)를 연결지어 놓는다.
- 삭제할 수 있도록 구현함.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- python shell을 키고, mock data들을 활용하면서 다양한 방식의 '참조'를 실제로 쳐보고, 눈으로 직접 확인. 내가 원하는 무언가에 찾아가는 방법에 대해 이번에야말로 한단계 더 이해가 된 것 같다.
- 댓글 기능을 구현하는 코드에 대해 찾아보고 공부해보면서, 어떤 구조로 짜야 하는 지를 깨달았으나 아직 명확한 이해가 되지는 않았다.
- 객체를 반환하는 것과 쿼리셋을 반환하는 것의 차이를 깨달았다. (쿼리셋은 하나씩 꺼내서 확인해줘야 한다..라는 생각으로 접근하게 됨)
- 모델링의 중요성을 정말 깨달았다. 또한, 처음 모델링 할 때 포스팅 관련해서 최대한 이해를 한 후에 모델링 작업이 함께 가줘야하는 것이었는데, 모델링을 너무 당연시하게 완료시킨 것이 오히려 많은 수정과 지체를 만든 패착이었음을 알았다.
<br />

## :: 기타 질문 및 특이 사항
- 경훈님, 리뷰 요청을 위한 PR을 올립니다. 감사합니다.

2022-01-13 12:42 UTC, Kang-kyunghun requested changes

2022-01-13 12:42 UTC, Kang-kyunghun commented on postings/urls.py
> +    path('/detail/<int:posting_id>', PostingDeatilView.as_view()),
```suggestion
    path('/<int:posting_id>', PostingDeatilView.as_view()),
```
detail 없이도 충분히 상품 정보 1개라는 의미를 가지고 있습니다.

2022-01-13 12:42 UTC, Kang-kyunghun commented on postings/views.py
> +            return JsonResponse({'message' : 'USER_DOESNOT_EXIST'}, status=400)
게시물의 상세 정보를 보는 곳이기 때문에 특정 user에 대한 로직이 필요 없습니다.
```suggestion

```

2022-01-13 12:42 UTC, Kang-kyunghun commented on postings/views.py
> +            user   = User.objects.get(id = posting.user_id)
```suggestion
            user   = posting.user
```
user를 posting으로부터 찾으려는 시도 너무 좋았습니다.
그런데, 이미 posting 객체로부터 user을 알 수 있습니다.

2022-01-13 12:42 UTC, Kang-kyunghun commented on postings/views.py
> +
불필요한 주석은 제거해 주세요.

2022-01-13 12:42 UTC, Kang-kyunghun commented on postings/views.py
> +            return JsonResponse({'message' : 'POSTING_DOESNOT_EXIST'}, status=400)
```suggestion
            return JsonResponse({'message' : 'POSTING_DOESNOT_EXIST'}, status=404)
```
does not exist 에러는 보통 404 코드를 사용합니다.

2022-01-13 12:42 UTC, Kang-kyunghun commented on postings/views.py
> +            user_id = request.user.id
```suggestion
            data    = json.loads(request.body)
            user_id = request.user.id
```

2022-01-13 12:42 UTC, Kang-kyunghun commented on postings/views.py
> +            Comment.objects.create(content = data['content'], posting_id=posting_id, user_id=user_id)
```suggestion
            Comment.objects.create(
                content    = data['content'], 
                posting_id = posting_id, 
                user_id    = user_id
            )
```

2022-01-13 12:42 UTC, Kang-kyunghun commented on postings/views.py
> +            } for comment in Posting.objects.get(id = posting_id).comment_set.all()]
1. : 기준으로 잘 정렬해 주세요.
2. 정렬 기준이 있나요? 최신순으로 나온다던지?
3. 페이지네이션도 추가해 주세요.

2022-01-13 12:43 UTC, Kang-kyunghun commented
코멘트 부분은 전체적으로 구두로 설명해 드리겠습니다.

2022-01-14 01:11 UTC, wsji91 commented
> 코멘트 부분은 전체적으로 구두로 설명해 드리겠습니다.

리뷰 감사드립니다 경훈님, 수정사항 잘 반영하여 진행할게요!

2022-01-15 09:26 UTC, Kang-kyunghun requested changes

2022-01-15 09:26 UTC, Kang-kyunghun commented on postings/tests.py
> +from my_settings     import SECRET_KEY, ALGORITHM
```suggestion
from django.test     import TestCase, Client

from postings.models import *
from users.models    import User
from my_settings     import SECRET_KEY, ALGORITHM
```
* 대신에 사용하는 모델을 import 해주세요.

2022-01-15 09:26 UTC, Kang-kyunghun commented on postings/views.py
> +            user   = posting.user
```suggestion
            posting.save()
            
            images = [{'image_id' : image.id, 'image_url' : image.image_url}
                      for image in posting.image_set.all()]
            user   = posting.user
```

2022-01-15 09:27 UTC, Kang-kyunghun commented
1. 디테일만 merge 할 수 있게 코멘트 관련 기능은 따로 브렌치 만들어서 다시 오려 주세요.
2. 데코레이터 merge 되었으니 데코레이터 적용 후 테스트 코드까지 오려주세요.

2022-01-17 08:32 UTC, Kang-kyunghun commented
LGTM

2022-01-17 08:32 UTC, merged