Add : 좋아요 기능 구현
wecode-bootcamp-korea/28-2nd-Barracks-backend pull request #6
Opened 2022-01-18 13:15 UTC by leeay3

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 좋아요 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 좋아요 기능 구현
  - 로그인 데코레이터 사용
  - post 메소드 사용하여 좋아요 기능 구현
  - get 메소드 사용하여 좋아요 누른 포스팅 리스트 

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

2022-01-19 04:41 UTC, Kang-kyunghun requested changes

2022-01-19 04:41 UTC, Kang-kyunghun commented on postings/urls.py
> +    path('like/<int:posting_id>/', PostingLikeView.as_view())
```suggestion
    path('/like', PostingLikeView.as_view())
```
위와 같이 수정하면 더 좋을 것 같습니다.

2022-01-19 07:31 UTC, leeay3 commented on postings/urls.py
> +    path('like/<int:posting_id>/', PostingLikeView.as_view())
넵 수정 완료 했습니다~

2022-01-20 03:42 UTC, Kang-kyunghun commented
LGTM~~!!

2022-01-20 03:42 UTC, merged